angular-architects/ngrx-toolkit

- libs/ngrx-toolkit/src/lib/with-call-state.ts
When trying to use `withCallState` in a `signalStore` and using `patchState` with the setter-functions, typescript will complain unless your store satisfies both `NamedCallStateSlice<Prop>` and `CallStateSlice` even if you only really get one of the two objects back. With this you should get conditional typing based on the input and not the union type of `NamedCallStateSlice<Prop>` and `CallStateSlice`.
E.g `setLoading('flights')` should give the type `NamedCallStateSlice<'flights'>` and not `NamedCallStateSlice<'flights'> | CallStateSlice`.
I appreciate any response as I think this would be nice if using `withCallState` for requests without `withDataService`.
> misc: conditional type narrowing on set callstate

- libs/ngrx-toolkit/src/lib/with-call-state.ts
This is a suggestion for an easier mapping of the state and signal types to the named (collection) types.
If you're ok with this I can take a look at the other mappings.
I've also reordered them so that the dependent type comes first.
> misc: refactored named types of withCallState

- apps/demo/src/app/flight-search/flight-store.ts
- apps/demo/src/app/todo-store.ts
- libs/ngrx-toolkit/src/index.ts
- libs/ngrx-toolkit/src/lib/with-devtools.ts
The name `patchState` is already used by the SignalStore. For better differentiation, a renaming was necessary.
`patchState` from this library is still available but marked as deprecated.
> feat(devtools): rename `patchState` to `updateState`

- libs/ngrx-toolkit/package.json
removing peerDependencies for angular
because they are transitive
fixes #51
> chore: depend only on @ngrx/signals

- libs/ngrx-toolkit/package.json
- libs/ngrx-toolkit/src/index.ts
- libs/ngrx-toolkit/src/lib/with-pagination.spec.ts
- libs/ngrx-toolkit/src/lib/with-pagination.ts
- package-lock.json
- package.json
This commit adds the implementation for local pagination in the `withPagination` function. It allows for displaying a subset of items from a larger collection, based on the current page and page size.
The `withPagination` function accepts an optional `collection` parameter to support multiple paginated collections. It calculates the selected page entities, total count, total pages, and page navigation array based on the provided options.
Additionally, utility functions like `gotoPage`, `setPageSize`, `nextPage`, `previousPage`, `firstPage`, and `setMaxPageNavigationArrayItems` are provided to easily update the pagination state.
> feat: Add local pagination feature

- libs/ngrx-toolkit/src/lib/with-undo-redo.ts
Perform a deep comparison to prevent duplicate entries on the stack. This can, for example, happen after an undo if the component sends back the undone filter to the store.
> fix(undo-redo): prevent duplicated entries on undo stack

- libs/ngrx-toolkit/README.md
Without this fix, the ``## Redux Connector for the NgRx Signal Store `createReduxState()` `` section is absorbed into the code block of the `## Storage Sync withStorageSync()` section.
Also this commit adds some closing `}` to the `withStorageSync` block.
> fix: close unterminated code block in `libs/ngrx-toolkit/README.md`

- README.md
- libs/ngrx-toolkit/src/lib/with-undo-redo.spec.ts
- libs/ngrx-toolkit/src/lib/with-undo-redo.ts
This pull requests closes issues [#81](https://github.com/angular-architects/ngrx-toolkit/issues/81) and  [#78](https://github.com/angular-architects/ngrx-toolkit/issues/78), while adding unit tests and docs for und-redo feature. Also for more manageable configs of the feature I have changed the typing of it, which allows for better type suggestions and checking.
> feat: add undo-redo skip and keys options, docs and unit tests

- README.md
- libs/ngrx-toolkit/README.md
I remembered seeing `withDataService` after I read an article that did something like it. I was going to tweak this to use `rxMethod` for my own project, but then I realized the doc pages were missing `updateAll`.
> docs: Add missing `updateAll` example to `withDataService` interface examples (root & lib)

- README.md
- libs/ngrx-toolkit/src/index.ts
- libs/ngrx-toolkit/src/lib/with-devtools.ts
> feat: withDevTools disabled in prod - tree-shaking docs

- libs/ngrx-toolkit/src/lib/with-data-service.spec.ts
Prerequisite to [feat: add support for observables to withDataService](https://github.com/angular-architects/ngrx-toolkit/pull/88)
I said that I would make tests for `withDataService` featuring support for observables. However, it would be good to have existing tests for the feature as it is currently with promises before the `withDataService` is further extended. 
Once I have a test for each method of the `interface DataService` with promises stubbed out then I'll bump this from a draft to a full PR. Tests are not my strong suit, so please roast these. 
edit: 
Progress/TODO 9/29/2024
- Happy path state changes are done
- Still need to
- Test loading state
- Test error state
> test(dataService): add basic tests for `withDataService`

- apps/demo/e2e/feature-factory.spec.ts
- apps/demo/src/app/app.component.html
- apps/demo/src/app/feature-factory/feature-factory.component.ts
- apps/demo/src/app/lazy-routes.ts
- docs/docs/extensions.md
- docs/docs/with-feature-factory.md
- docs/sidebars.ts
- libs/ngrx-toolkit/src/index.ts
- libs/ngrx-toolkit/src/lib/with-feature-factory.spec.ts
- libs/ngrx-toolkit/src/lib/with-feature-factory.ts
The `withFeatureFactory()` function allows
passing properties, methods, or signals from
a SignalStore to a feature. It is an advanced
feature, primarily targeted for library
authors for SignalStore features.
Its usage is very simple. It is a function which
gets the current store:
```typescript
function withSum(a: Signal<number>, b: Signal<number>) {
return signalStoreFeature(
withComputed(() => ({
sum: computed(() => a() + b())
}))
);
}
signalStore(
withState({ a: 1, b: 2 }),
withFeatureFactory((store) => withSum(store.a, store.b))
);
```
> feat: add `withFeatureFactory()`

- docs/docs/with-feature-factory.md
Imports that aren't directly relevant to the library or a given example can omit imports for brevity
> docs: remove non-library import snippet

- docs/README.md
- docs/docs/with-data-service.md
- docs/docs/with-feature-factory.md
- docs/docs/with-immutable-state.md
- docs/docs/with-storage-sync.md
- docs/docs/with-undo-redo.md
I looked at the docs snippet after noticing the last PR and noticed two things
- One snippet needed indents (`withDataService`)
- Some snippets didn't have a language, or were not consistent with others
> docs: make snippet langs consistent & fix example indent

- libs/ngrx-toolkit/src/lib/devtools/internal/devtools-syncer.service.ts
- libs/ngrx-toolkit/src/lib/devtools/tests/helpers.spec.ts
- libs/ngrx-toolkit/src/lib/devtools/tests/naming.spec.ts
- libs/ngrx-toolkit/src/lib/devtools/with-devtools.ts
devtools use a static variable to store
the existing names of SignalStore classes.
In SSR, this fails because it registers
a second time in the browser and runs
see this the same name already exists.
> fix(devtools): fix existing name error in SSR

- docs/docs/create-redux-state.md
- docs/docs/with-conditional.md
- docs/docs/with-data-service.md
- docs/docs/with-devtools.md
- docs/docs/with-feature-factory.md
- docs/docs/with-immutable-state.md
- docs/docs/with-redux.md
- docs/docs/with-reset.md
- docs/docs/with-storage-sync.md
- docs/docs/with-undo-redo.md
Issue: docs: add import to doc pages #155
https://github.com/angular-architects/ngrx-toolkit/issues/155
> docs: add `import` statements to doc pages

- docs/docs/with-reset.md
- docs/sidebars.ts
I saw `withReset` was not on the sidenav
Adjacent to the imports at the top of the page PR
- I added an import like in the other PR but in this branch
- Setting this as a draft as my open question in the imports PR applies to `setResetState()`
> docs: add `withReset` to sidenav + add imports to `withReset`

- libs/ngrx-toolkit/src/lib/devtools/tests/types.spec.ts
- libs/ngrx-toolkit/src/lib/devtools/with-devtools.ts
This fixes an issue with SignalStore's used to extend from, where `withDevtools` messed up the typing.
Closes: #164, #165
> fix(devtools): set types of `withDevtools` to `EmptyFeatureResult`

- libs/ngrx-toolkit/src/lib/with-call-state.spec.ts
- libs/ngrx-toolkit/src/lib/with-call-state.ts
feat: Enhanced `withCallState` to accept mutliple collection configuration
For #147 
I have not tested it but happy to help if in case it didn't work as expected
thanks
> feat: Enhanced `withCallState` to accept mutliple collection configuration

- docs/docs/extensions.md
- docs/docs/with-call-state.md
- docs/sidebars.ts
Add comprehensive documentation for withCallState feature explaining:
- Basic usage pattern
- Named collection support
- Multiple collections handling
- Helper methods and state types
- Usage examples in components
> docs: add `withCallState` feature documentation

- libs/ngrx-toolkit/src/lib/with-data-service.spec.ts
- libs/ngrx-toolkit/src/lib/with-data-service.ts
Providing collection name to `withDataService` now requires providing `withCallState` with the same collection name, otherwise type error.
This is also a small alignment with `withDataService` for signature without collection name. (if it has no collection name but `withCallState` has - type error)
Hope this PR will be useful.
> feat: Enhanced `withDataService` to require callState collection name

- docs/docs/extensions.md
- docs/docs/with-redux.md
- libs/ngrx-toolkit/src/lib/with-redux.ts
NgRx introduced events in 19.2: https://dev.to/ngrx/announcing-events-plugin-for-ngrx-signalstore-a-modern-take-on-flux-architecture-4dhn. Support for `withRedux` in the toolkit is marked as deprecated with this change.
> docs: deprecate `withRedux`

- libs/ngrx-toolkit/src/lib/with-undo-redo.spec.ts
- libs/ngrx-toolkit/src/lib/with-undo-redo.ts
> fix(undo-redo): clearStack should also clear the previous item

- libs/ngrx-toolkit/src/lib/with-undo-redo.spec.ts
- libs/ngrx-toolkit/src/lib/with-undo-redo.ts
This pull request fixes bug [#190](https://github.com/angular-architects/ngrx-toolkit/issues/190) and causes the undo/redo feature to synchronise instead of operating asynchronously.
> fix #190: make withUndoRedo sync with watchState instead of effect

- docs/docs/mutations.md
- docs/src/components/MutationsVideo/index.tsx
- docs/src/components/MutationsVideo/styles.module.css
Add @manfredsteyer's webinar, timestamped for the mutations part of the talk.
> docs(mutations): embed mutations webinar
